preserve_hierarchy: true
files:
  - source: /ProjectLighthouse.Localization/*.resx
    translation: /ProjectLighthouse.Localization/%file_name%.%locale%.%file_extension%
    ignore:
      - /ProjectLighthouse.Localization/%file_name%.*.%file_extension%
